### PR TITLE
Publishing news to twitter

### PR DESCRIPTION
**Pull request by prodex**
issue #26

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by samdark** [comment]
Set up it on the server. Will announce and add to website a bit later.

**Comment by prodex** [comment]
What will happen with yiifeed.com and yiiframework.ru after release yiiframework.com?

**Comment by samdark** [comment]
They will remain as is. News at yiiframework.com will be official releases only. Not community things. International communities will stay as is as well. .com is primarily English.

**Pull request merged**
