### PR TITLE
GFM should not use comment adjustment for article rendering

### PR DESCRIPTION
**Pull request by cebe**
otherwise news text formatting will be a bit weird.

### CODE REVIEW

**Comment by samdark** [comment]
How weird exactly?

**Comment by samdark** [comment]
`gfm-comment` is about newlines and I think they're appropriate when writing posts as well.

**Comment by cebe** [comment]
Example:

bildschirmfoto von 2016-03-18 15 36 09

I do not think newlines should be kept in articles, if you write HTML you also need to be explicit about `<br/>` tags. I do not see any use case for line breaks. If you really need one inside a praragraph you can add it by adding two spaces but normally paragraph should not explicitly break somewhere.

Here is another example of wrong breaking:

bildschirmfoto von 2016-03-18 15 42 37

**Comment by samdark** [comment]
OK :+1:

**Pull request merged**
